### PR TITLE
Additional login methods using firebase auth

### LINKED ISSUE #4: Add Additional Login Methods Using Firebase Authentication (Minimum 3 Providers)
**Description**  
The LeetPath website currently supports limited login options (Email and Google). To improve user convenience and accessibility, we need to integrate additional login methods such as Facebook, GitHub, and others using Firebase Authentication.  

#### Requirements  
1. **Integrate Additional Providers**  
   - Add support for the following login methods using Firebase:  
     - Facebook  
     - GitHub, wtc

2. **Update Firebase Configuration**  
   - Enable the selected providers in the Firebase console.  
   - Update the Firebase configuration in the project to include the necessary API keys and secrets.  

3. **Frontend Changes**  
   - Add buttons or icons for the new login methods on the login page.  
   - Style the buttons to maintain consistency with the website's design.  

#### Acceptance Criteria  
- Users can log in using other sign in methods seamlessly.  
- The login page UI clearly displays the new options.  

- Ensure that the OAuth credentials (API keys, secrets) are stored securely and not exposed in the codebase.

### PR DESCRIPTION
**Pull request by JrGkOG**
In this PR I have added 

1. Integrate Additional Providers with proper Icons 
   -> Github 
   -> Facebook
   -> Microsoft
   

Register Route

image

Login Route 

image

2.Update Firebase Configuration

image

Videos Logging in with Different Providers 

**Github**

https://github.com/user-attachments/assets/fbe3a7e2-16d4-4b01-bf4c-aed19c5d5991

**Facebook**

https://github.com/user-attachments/assets/ceb4fc30-5142-4101-b35a-f1839f25aaa4

**Microsoft**

https://github.com/user-attachments/assets/d489b9eb-b260-49a1-be54-6da67ec639d7

Handling Cases where User has same email in different Providers.

Over here user with the email has already been there with Facebook provider and he try's to login with GitHub now.

https://github.com/user-attachments/assets/a3b4df93-5677-4cb9-89d7-37a1593307cb

3.Made .gitignore centralized 
3.Removed .env files to maintain security

solves #4

### CODE REVIEW

**Comment by JrGkOG** [comment]
Hi, 
@VishalTheHuman please review this PR

**Review by VishalTheHuman — COMMENTED** [review]
looks good

**Comment by amri-tah** [comment]
Nice work @adofm! 🚀

**Comment by JrGkOG** [comment]
> Nice work @adofm! 🚀

Thanks

**Pull request merged**
